ca-cwds/cals-api

src/main/java/gov/ca/cwds/cals/service/mapper/FacilityChildrenMapper.java
src/main/java/gov/ca/cwds/cals/service/mapper/PersonDTOMapper.java

The mapper warning was eliminated

Cleanup, refactor method name

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/java/gov/ca/cwds/cals/inject/CountiesServiceBackendResource.java
src/main/java/gov/ca/cwds/cals/inject/DataAccessModule.java
src/main/java/gov/ca/cwds/cals/inject/MappingModule.java
src/main/java/gov/ca/cwds/cals/inject/ResourcesModule.java
src/main/java/gov/ca/cwds/cals/inject/ServicesModule.java
src/main/java/gov/ca/cwds/cals/persistence/dao/cms/CountiesDao.java
src/main/java/gov/ca/cwds/cals/service/CountiesService.java
src/main/java/gov/ca/cwds/cals/service/dto/CountiesDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/CountyDTO.java
src/main/java/gov/ca/cwds/cals/service/mapper/CountyMapper.java
src/main/java/gov/ca/cwds/cals/web/rest/CountiesResource.java
src/main/java/gov/ca/cwds/cals/web/rest/CountyResource.java
src/test/java/gov/ca/cwds/cals/web/rest/CountiesResourceTest.java
src/test/resources/config/test-cals-api.yml

#145619107 counties dictionary

---

Jenkinsfile
build.gradle
gradle.properties
src/test/java/gov/ca/cwds/cals/BaseCalsApiIntegrationTest.java
src/test/java/gov/ca/cwds/cals/web/rest/FacilityComplaintResourceTest.java
src/test/java/gov/ca/cwds/cals/web/rest/RestClientTestRule.java

Tests support external URL for testing cals API.
Gradle task "integrationTest" was created.
New stage in Jenkins pipeline was created for Integration test

#146267417

---

build.gradle
config/cals-api.yml
src/main/java/gov/ca/cwds/cals/CalsApiApplication.java
src/main/java/gov/ca/cwds/cals/CalsApiConfiguration.java
src/main/java/gov/ca/cwds/cals/Constants.java
src/main/java/gov/ca/cwds/cals/inject/AgeGroupTypesServiceBackendResource.java
src/main/java/gov/ca/cwds/cals/inject/CalsnsHibernateBundle.java
src/main/java/gov/ca/cwds/cals/inject/CalsnsSessionFactory.java
src/main/java/gov/ca/cwds/cals/inject/DataAccessModule.java
src/main/java/gov/ca/cwds/cals/inject/ResourcesModule.java
src/main/java/gov/ca/cwds/cals/inject/ServicesModule.java
src/main/java/gov/ca/cwds/cals/persistence/dao/calsns/AgeGroupTypeDao.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/AgeGroupType.java
src/main/java/gov/ca/cwds/cals/service/AgeGroupTypesService.java
src/main/java/gov/ca/cwds/cals/service/dto/AgeGroupTypesDTO.java
src/main/java/gov/ca/cwds/cals/web/rest/AgeGroupTypeResource.java
src/test/java/gov/ca/cwds/cals/BaseCalsApiIntegrationTest.java
src/test/java/gov/ca/cwds/cals/web/rest/AgeGroupTypeResourceTest.java
src/test/resources/config/test-cals-api.yml
src/test/resources/fixtures/age-group-types-response.json

REST API resource AgeGroupType dictionary implementation
Integration test

#146899687

---

jdl/rfa.jh

Adjusted names createDatetime and updateDatetime

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/java/gov/ca/cwds/cals/inject/DataAccessModule.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/BaseDictionary.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/NameType.java
src/main/java/gov/ca/cwds/cals/service/mapper/AddressMapper.java
src/main/java/gov/ca/cwds/cals/web/rest/DictionariesResource.java
src/test/java/gov/ca/cwds/cals/web/rest/DictionariesResourceTest.java
src/test/resources/fixtures/dictionary-name-type-response.json

add NameType dictionary resource

#147247251

---

src/main/java/gov/ca/cwds/cals/persistence/model/cms/rs/ReplicatedPlacementHome.java
src/test/resources/fixtures/facility-by-id-response.json

Facility load iteration 3.2

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/java/gov/ca/cwds/cals/inject/DataAccessModule.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/ApplicantRelationshipType.java
src/main/java/gov/ca/cwds/cals/web/rest/DictionariesResource.java
src/test/java/gov/ca/cwds/cals/web/rest/DictionariesResourceTest.java
src/test/resources/fixtures/dictionary/applicant-relationship-type-response.json

#147648757 created REST API resource ApplicantRelationshipType dictionary

---

src/main/java/gov/ca/cwds/cals/service/rfa/RFA1aApplicantService.java
src/main/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aApplicantResource.java

#147207261

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/java/gov/ca/cwds/cals/inject/DataAccessModule.java
src/main/java/gov/ca/cwds/cals/inject/RFA1aMinorChildrenCollectionServiceBackendResource.java
src/main/java/gov/ca/cwds/cals/inject/RFA1aMinorChildrenServiceBackendResource.java
src/main/java/gov/ca/cwds/cals/inject/ResourcesModule.java
src/main/java/gov/ca/cwds/cals/inject/ServicesModule.java
src/main/java/gov/ca/cwds/cals/persistence/dao/ScrollableResultsIterator.java
src/main/java/gov/ca/cwds/cals/persistence/dao/calsns/RFA1aMinorChildDao.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/ApplicantsRelationshipJsonType.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/MinorChild.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/MinorChildJsonType.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/RFA1aApplicant.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/RFA1aBaseEntity.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/RFA1aForm.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/RFA1aMinorChild.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/package-info.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/MinorChildrenDTO.java
src/main/java/gov/ca/cwds/cals/service/rfa/RFA1aApplicantService.java
src/main/java/gov/ca/cwds/cals/service/rfa/RFA1aApplicantsCollectionService.java
src/main/java/gov/ca/cwds/cals/service/rfa/RFA1aMinorChildService.java
src/main/java/gov/ca/cwds/cals/service/rfa/RFA1aMinorChildrenCollectionService.java
src/main/java/gov/ca/cwds/cals/service/rfa/RFA1aServiceHelper.java
src/main/java/gov/ca/cwds/cals/web/rest/parameter/RFA1aMinorChildrenParameterObject.java
src/main/java/gov/ca/cwds/cals/web/rest/rfa/ApplicantsRelationshipResource.java
src/main/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aApplicantResource.java
src/main/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aFormsResource.java
src/main/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aMinorChildrenResource.java
src/main/java/gov/ca/cwds/cals/web/rest/rfa/ResidenceResource.java
src/test/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/package-info.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aMinorChildrenResourceTest.java

REST Resource, Persistence, Tests

#147207541 minor children

---

src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/ApplicantJsonType.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/RFA1aApplicant.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/ApplicantsDTO.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aApplicantResourceTest.java

#147207261 applicants

---

src/main/java/gov/ca/cwds/cals/service/DictionariesService.java
src/main/java/gov/ca/cwds/cals/service/dto/DictionaryValuesDTO.java
src/main/java/gov/ca/cwds/cals/web/rest/DictionariesResource.java

Add Swagger documentation to Dictionaries

#147632481

---

src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/Address.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/Residence.java
src/test/resources/fixtures/rfa/rfa-1a-residence-request.json

Model was changed according to new contract

#148152007

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/java/gov/ca/cwds/cals/inject/DataAccessModule.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/MarriageTerminationReason.java
src/main/java/gov/ca/cwds/cals/web/rest/DictionariesResource.java
src/test/java/gov/ca/cwds/cals/web/rest/DictionariesResourceTest.java
src/test/resources/fixtures/dictionary/marriage-termination-reason-response.json

REST Resource, Persistence, Tests

#146909349

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/java/gov/ca/cwds/cals/inject/RFA1aApplicantsDeclarationServiceBackedResource.java
src/main/java/gov/ca/cwds/cals/inject/ResourcesModule.java
src/main/java/gov/ca/cwds/cals/inject/ServicesModule.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/ApplicantsDeclaration.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/RFA1aForm.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/package-info.java
src/main/java/gov/ca/cwds/cals/service/rfa/RFA1aApplicantsDeclarationService.java
src/main/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aApplicantsDeclarationResource.java
src/test/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/package-info.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aApplicantsDeclarationResourceTest.java

Applicants Declaration REST Resource, Persistence, Tests

#147228135

---

src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/BaseDictionary.java

#148626629

---

src/test/resources/fixtures/dictionary/education-level-type-response.json
src/test/resources/fixtures/rfa/rfa-1a-applicant.json

Update fixtures for the Education Level dictionary

#148639143

---

src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/LegacyComplaintDictionary.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/PhoneNumberType.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/ShortCodeComplaintDictionary.java
src/test/resources/fixtures/dictionary/phone-number-type-response.json

Add ShortCodeComplaintDictionary class
Update fixtures

#148639089

---

src/test/resources/fixtures/dictionary/name-type-response.json

#148639043

---

build.gradle
src/test/java/gov/ca/cwds/cals/DictionaryLiquibaseGenerator.java
src/test/resources/DictItems.csv
src/test/resources/LegacyComplaintDictionaryLiquibaseTemplate.vm
src/test/resources/fixtures/dictionary/language-type-response.json
src/test/resources/fixtures/rfa/demo-3-2/rfa-1a-residence.json
src/test/resources/fixtures/rfa/rfa-1a-residence-request.json
src/test/resources/fixtures/rfa/rfa-1a-residence-response.json
src/test/resources/fixtures/rfa/rfa-1a.json

Liquibase generator
Update fixture

#148639033

---

src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/GenderType.java
src/test/resources/fixtures/dictionary/gender-type-response.json

Update GenderDictionary and fixture

#148639023

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/java/gov/ca/cwds/cals/inject/DataAccessModule.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/NamePrefixType.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/AdultChildDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/ApplicantDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/FormerSpouseDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/MinorChildDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/OtherAdultDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/PersonNameDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/RFA1bFormDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/ReferencesDTO.java
src/main/java/gov/ca/cwds/cals/web/rest/DictionariesResource.java
src/test/java/gov/ca/cwds/cals/web/rest/DictionariesResourceTest.java
src/test/resources/fixtures/dictionary/name-prefix-type-response.json
src/test/resources/fixtures/rfa/demo-3-2/rfa-1a-applicant1.json
src/test/resources/fixtures/rfa/demo-3-2/rfa-1a-applicant2.json
src/test/resources/fixtures/rfa/demo-3-2/rfa-1a-minor_children.json
src/test/resources/fixtures/rfa/demo-3-2/rfa-1a-residence.json
src/test/resources/fixtures/rfa/rfa-1a-applicant.json
src/test/resources/fixtures/rfa/rfa-1a-applicants-history.json
src/test/resources/fixtures/rfa/rfa-1a-minor-children.json
src/test/resources/fixtures/rfa/rfa-1a-other-adults.json
src/test/resources/fixtures/rfa/rfa-1a-references.json
src/test/resources/fixtures/rfa/rfa-1a-residence-request.json
src/test/resources/fixtures/rfa/rfa-1a-residence-response.json
src/test/resources/fixtures/rfa/rfa-1a.json
src/test/resources/fixtures/rfa/rfa-1b-form.json

NamePrefixType dictionary
RFA API and Tests was updated

#148725979

---

src/main/java/gov/ca/cwds/cals/service/dto/rfa/PhoneDTO.java
src/test/java/gov/ca/cwds/cals/service/BeanValidationTestSupport.java
src/test/java/gov/ca/cwds/cals/service/dto/rfa/PhoneDTOTest.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aApplicantResourceTest.java
src/test/resources/fixtures/rfa/rfa-1a-applicant.json

Phone extansion field was added,
validation test was created

#148725477

---

config/cals-api-lis-connx.yml
config/cals-api.yml

#149283487 Integrate logging mechanisms implemented in API

---

src/main/java/gov/ca/cwds/cals/service/dto/FacilityDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/PersonPhoneDTO.java
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityMapper.java
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityPostMappingProcessor.java
src/main/java/gov/ca/cwds/cals/service/mapper/PhoneMapper.java
src/main/java/gov/ca/cwds/cals/service/mapper/PhoneMapperDecorator.java

rename PhoneDTO to PersonPhoneDTO for fixing swagger documentation issue

148725477 Phone Extension

---

src/main/java/gov/ca/cwds/cals/service/mapper/TrailingSpacesRemovalPostMappingProcessor.java

Revert "Cals jobs pi 3.5"

---

src/main/java/gov/ca/cwds/cals/service/mapper/PlacementHomeMapper.java
src/test/resources/dbunit/PlacementHome.xml
src/test/resources/dbunit/PlacementHomeUC.xml

(cherry picked from commit cb9ff18)

#150720776 Making License Number empty instead of NULL

---

src/main/java/gov/ca/cwds/cals/service/dto/rfa/AdoptionHistoryDTO.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/BaseRFAIntegrationTest.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aAdoptionHistoryResourceTest.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/helper/AdoptionHistoryHelper.java
src/test/resources/fixtures/rfa/rfa-1a-adoption-history-small.json

#151228616 fix for ability to set null Foster Care/License History boolean values

---

config/shiro.ini
config/shiro_v2.ini

default configuration for dev mode

default shiro configuration

---

config/shiro.ini
config/shiro_jwt.ini

Revert "default shiro configuration"

---

build.gradle
config/cals-api.yml
config/shiro_jwt.ini
src/test/java/gov/ca/cwds/cals/web/rest/ExceptionHandlingResponseTest.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aApplicantResourceTest.java
src/test/java/gov/ca/cwds/cals/web/rest/utils/AssertFixtureUtils.java
src/test/resources/fixtures/exception/business-validation-exception.json
src/test/resources/fixtures/exception/technical-validation-exception.json
src/test/resources/fixtures/rfa/validation/applicant-duplicate-name-violation-response.json
src/test/resources/fixtures/rfa/validation/applicant-duplicate-phone-numbers-response.json
src/test/resources/fixtures/rfa/validation/applicant-duplicate-phone-numbers-with-extensions-response.json
src/test/resources/fixtures/rfa/validation/applicant-more-then-one-preferred-number-response.json
src/test/resources/fixtures/rfa/validation/validation_error_response.json

Revert "Revert "150896204 update shiro security library""

---

config/shiro.ini
config/shiro_v2.ini

Revert "Revert "default shiro configuration""

---

Dockerfile

Revert "Keystore removed from application"

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/java/gov/ca/cwds/cals/Utils.java
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityMapper.java
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityPostMappingProcessor.java
src/main/java/gov/ca/cwds/cals/service/mapper/PhoneMapperDecorator.java

fixed phone mapper delegate for LIS

CAL1-57 Facility search issue in Integration

---

src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/CountyType.java
src/test/resources/fixtures/dictionary/county-type-response.json

User Story: https://osi-cwds.atlassian.net/browse/CALS-5452

CALS-5452: county list ordered by name

---

build.gradle
src/test/resources/fixtures/dictionary/facility-type-response.json

updated cals-data-model version;

---

src/main/java/gov/ca/cwds/cals/persistence/model/lisfas/LisFacFile.java
src/main/java/gov/ca/cwds/cals/service/FacilityService.java

…egion_do and fac_region_co were temporarily removed from lis_fac_file

CALS-5551 fixed LIS facilities

---

src/main/java/gov/ca/cwds/cals/service/dto/rfa/IdentifiedChildDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/RFA1bFormDTO.java

Revert "CALS-5609, CALS-5608: validations added to RFA 1B, 1C"

---

build.gradle
src/main/java/gov/ca/cwds/cals/service/builder/PlacementHomeEntityAwareDTOBuilder.java

CALS-5182 

---

build.gradle

https://osi-cwds.atlassian.net/browse/CALS-5154
DocTool rule R - 02974 SCP - Primary Provider Check

 CALS-5154: DocTool rule R - 02974 SCP - Primary Provider Check

---

build.gradle
config/cals-api-lis-connx.yml
config/cals-api.yml
config/shiro.ini
config/shiro_v2.ini

Revert "TPT2-658: Perry v2 support"

---

src/main/resources/form-submission-rules/required-fields-validation.drl
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aRequiredFieldsValidationTest.java

Fix problem with blank Mailing Address

CALS-5685 required fields validation

---

build.gradle
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityChildMapper.java
src/test/resources/fixtures/facility-children-response-assigned-worker-present.json

User Story: https://osi-cwds.atlassian.net/browse/CALS-5520

CALS-5520: Impossible to fetch children for facility Ady1UyD01w in INT

---

build.gradle
docker/docker-compose.yml
src/main/java/gov/ca/cwds/cals/CalsApiApplication.java
src/main/java/gov/ca/cwds/cals/inject/ApplicationModule.java
src/main/java/gov/ca/cwds/cals/inject/ServicesModule.java
src/main/java/gov/ca/cwds/cals/service/FacilityChildCollectionService.java
src/main/java/gov/ca/cwds/cals/service/FacilityService.java
src/main/java/gov/ca/cwds/cals/web/rest/FacilityResource.java
src/test/java/gov/ca/cwds/cals/web/rest/FacilityResourceTest.java
src/test/resources/security/principal-no-privilages.json
src/test/resources/security/principal-priv-CWS_Case_Management_System.json
src/test/resources/security/principal-priv-Resource_Management.json

StaticAuthorizer was applied to the Facility Resource

CALS-5651 Read Authorization for getFacility API

---

src/main/java/gov/ca/cwds/cals/persistence/dao/fas/ComplaintReportLic802Dao.java
src/main/java/gov/ca/cwds/cals/service/ComplaintService.java
src/main/java/gov/ca/cwds/cals/web/rest/FacilityComplaintResource.java
src/main/java/gov/ca/cwds/cals/web/rest/parameter/FacilityComplaintParameterObject.java
src/test/java/gov/ca/cwds/cals/web/rest/FacilityComplaintResourceTest.java

https://osi-cwds.atlassian.net/browse/CALS-5552
change facilityId request parameter type from Integer to String;
related code changes;
code formatting according to google checkstyle plugin;
added test for case when facility id is alphanumeric;

CALS-5552: Number Format Exception for Facility Complaints in INT

---

Jenkinsfile
README.md
config/cals-api-lis-connx.yml
config/cals-api.yml

- https://osi-cwds.atlassian.net/browse/CALS-5742
Readme updated with new configuration parameters

CALS-5654: readme updated with new configuration parameters

---

build.gradle
src/main/java/gov/ca/cwds/cals/service/CwsFacilityService.java
src/test/java/gov/ca/cwds/cals/web/rest/facility/FacilityChildAuthorizationTest.java
src/test/java/gov/ca/cwds/cals/web/rest/facility/FacilityChildResourceTest.java
src/test/java/gov/ca/cwds/cals/web/rest/facility/FacilityResourceTest.java

- https://osi-cwds.atlassian.net/browse/CALS-NNNN
New version of api core. Get Facility by wrong CWS/CMS Id fixed to return 404

CALS-5820: new version of api core. Get Facility by wrong CWS/CMS Id fixed to return 404

---

Jenkinsfile-cals-api-tests

- https://osi-cwds.atlassian.net/browse/CALS-5820
Default values for PreInt integration test updated

CALS-5820: default values for PreInt integration test updated

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/resources/form-submission-rules/form-submission-validation.drl
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aSubmitValidationTest.java
src/test/resources/fixtures/rfa/validation/other-adult-has-no-date-of-birth.json

- https://osi-cwds.atlassian.net/browse/CALS-5865
Implement backend for Other Adults Residing in the Home Required Validation on Submit
N/A
N/A

CALS-5865: other adults validation in RFA 1A

---

build.gradle
src/main/java/gov/ca/cwds/cals/persistence/model/fas/FacilityInformation.java
src/main/java/gov/ca/cwds/cals/persistence/model/fas/LpaInformation.java
src/main/java/gov/ca/cwds/cals/service/FasFacilityService.java
src/main/java/gov/ca/cwds/cals/service/dto/FacilityVisitDTO.java
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityVisitMapper.java
src/test/java/gov/ca/cwds/cals/web/rest/facility/FacilityResourceTest.java
src/test/resources/fixtures/facility/facility-by-license-number-response.json

- https://osi-cwds.atlassian.net/browse/CALS-4319
Facility API test updated to use data from Integration environment. Query to extract LPA information from FAS changed.
N/A
N/A

CALS-4319: Query to extract LPA information from FAS changed

---

Jenkinsfile-complete.groovy
Jenkinsfile-pull-request.groovy
src/test/java/gov/ca/cwds/cals/web/rest/rfa/DraftApplicationsTest.java

- https://osi-cwds.atlassian.net/browse/CALS-5888
Pipeline enhancement. Stages switched to split build, test and publish

Pipeline enhancement. Stages switched to split build, test and publish

---

config/cals-api-lis-connx.yml

Healthcheck queries changed in production configuration to use system table instead of Placement Home table to prevent locks on production data.
This is just configuration change so not tests needed

Healthcheck queries changed to DB2 updated

---

Jenkinsfile-complete.groovy
Jenkinsfile-pull-request.groovy

- https://osi-cwds.atlassian.net/browse/CALS-5888
Pull request pipeline reduced to run only build, unit tets and SonarQube

Pipeline enhancement

---

build.gradle
src/main/java/gov/ca/cwds/cals/BaseCalsApiApplication.java
src/main/java/gov/ca/cwds/cals/web/rest/filters/RequestResponseLoggingFilter.java

RequestResponseLoggingFilter turned off to reduce amount of logging. This filter currently log responses which can be large.

Logging filter turned off to reduce logging

---

README.md
build.gradle
config/cals-api.yml
config/shiro.ini
src/main/java/gov/ca/cwds/cals/service/rfa/RFA1aFormService.java

- https://osi-cwds.atlassian.net/browse/CALS-5812

CALS-5812: shiro yaml config

---

build.gradle
src/main/java/gov/ca/cwds/cals/persistence/model/fas/ComplaintReportLic802.java
src/main/java/gov/ca/cwds/cals/persistence/model/fas/FacilityInformation.java
src/main/java/gov/ca/cwds/cals/persistence/model/fas/LpaInformation.java
src/main/java/gov/ca/cwds/cals/persistence/model/fas/Rr809Dn.java
src/main/java/gov/ca/cwds/cals/persistence/model/fas/Rrcpoc.java

- https://osi-cwds.atlassian.net/browse/CALS-5922
Currently CALS API and Facility jobs are using old database and need to switch to newly created FAS database.

CALS-5922: Complaints report entity changed to support FAS-ChildRes-Live database structure

---

config/cals-api.yml
src/main/java/gov/ca/cwds/cals/persistence/model/fas/FacilityInformation.java

https://osi-cwds.atlassian.net/browse/CALS-5922
FacilityInformation FAS table fixed to remove unexisting dt_edeted

CALS-5922: FacilityInformation FAS table fixed to remove unexisting dt_edeted

---

build.gradle
src/main/java/gov/ca/cwds/cals/persistence/model/fas/FacilityInformation.java

- https://osi-cwds.atlassian.net/browse/CALS-5922
FacilityInformation FAS table fixed to remove unneeded attributes

CALS-5922: FacilityInformation FAS table fixed to remove unneeded attributes

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/resources/form-submission-rules/required-fields-validation.drl
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1bSubmitValidationTest.java
src/test/java/gov/ca/cwds/cals/web/rest/utils/AssertFixtureUtils.java
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-conviction-CA-details-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-conviction-CA-disclosure-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-conviction-CA-offense-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-conviction-CA-when-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-conviction-CA-where-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-conviction-outside-CA-details-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-conviction-outside-CA-disclosure-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-conviction-outside-CA-offense-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-conviction-outside-CA-when-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-conviction-outside-CA-where-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-crime-details-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-crime-disclosure-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-crime-offense-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-crime-when-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-crime-where-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-has-no-county-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-has-no-first-name-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-has-no-last-name-response.json
src/test/resources/fixtures/rfa/validation/rfa1b/fra1b-other-states-is-required-response.json

- https://osi-cwds.atlassian.net/browse/CALS-5920

CALS-5920: Develop backend validation for RFA 1B

---

src/main/java/gov/ca/cwds/cals/Constants.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/IdentifiedChildDTO.java
src/main/resources/form-submission-rules/required-fields-validation.drl
src/test/java/gov/ca/cwds/cals/web/rest/rfa/BaseRFAIntegrationTest.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1cSubmitValidationTest.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/helper/FormCHelper.java
src/test/resources/fixtures/rfa/validation/rfa1c/fra1c-dob-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1c/fra1c-first-name-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1c/fra1c-in-home-is-required-response.json
src/test/resources/fixtures/rfa/validation/rfa1c/fra1c-last-name-is-required-response.json

- https://osi-cwds.atlassian.net/browse/CALS-5933

CALS-5933: Develop backend validation for RFA 1C

---

build.gradle
gradle.properties
src/test/java/gov/ca/cwds/IntegrationTestSuite.java

N/A
Integration test suite was added to collect all the integration tests in one place
N/A
N/A

Integration test suite

---

build.gradle
config/cals-api-lis-connx.yml
config/cals-api.yml

- https://osi-cwds.atlassian.net/browse/CALS-5942
health check queries changed to use lite weight SQL queries to eliminate possible impact on databases

CALS-5942: health check queries changed to use lite weight SQL queries

---

src/main/java/gov/ca/cwds/cals/service/dto/rfa/MinorChildDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/RelationshipToApplicantDTO.java
src/main/resources/form-submission-rules/required-fields-validation.drl
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aRequiredFieldsValidationTest.java
src/test/resources/fixtures/rfa/rfa-1a-minor-children.json

Revert "CALS-5990 Change backend API for RFA Minor child"

---

src/main/java/gov/ca/cwds/cals/service/CwsFacilityService.java
src/main/java/gov/ca/cwds/cals/service/FacilityTypeService.java
src/main/java/gov/ca/cwds/cals/service/LisFacilityService.java

LIS facility related fixes;
- https://osi-cwds.atlassian.net/browse/CALS-NNNN

CALS-5936: No Facilities Found when Using Facility Type as a Filter Criteria

---

src/main/java/gov/ca/cwds/cals/service/LisFacilityService.java
src/main/java/gov/ca/cwds/cals/web/rest/FacilityInspectionsResource.java
src/test/java/gov/ca/cwds/cals/web/rest/facility/FacilityInspectionsTest.java

- https://osi-cwds.atlassian.net/browse/AARA-115
Static authorization added to Get Facility Inspections API. Staff person with CWS Case Management System and Resource Management privileges will be able to access the API,
- [ x] I have included unit tests 
- [x ] New feature (non-breaking change which adds functionality)
No
No

AARA-115: Authorization added to Get Facility Inspections API

---

src/main/java/gov/ca/cwds/cals/service/dto/rfa/MinorChildDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/rfa/RelationshipToApplicantDTO.java
src/main/resources/form-submission-rules/required-fields-validation.drl
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aRequiredFieldsValidationTest.java
src/test/resources/fixtures/rfa/rfa-1a-minor-children.json

- https://osi-cwds.atlassian.net/browse/AARA-244
Change backend API for RFA Minor child

CALS-5990 Change backend API for RFA Minor child

---

src/main/java/gov/ca/cwds/cals/service/dto/FacilityChildDTO.java
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityChildMapper.java
src/test/resources/fixtures/facility/authorization/get-children-sealed.json
src/test/resources/fixtures/facility/facility-child-response.json
src/test/resources/fixtures/facility/facility-children-response-assigned-worker-present.json
src/test/resources/fixtures/facility/facility-children-response.json

https://osi-cwds.atlassian.net/browse/SEAR-84
Added client id for displaying on front end
No configuration changes needed
No technical debt added

SEAR-91 added display client id property

---

src/main/java/gov/ca/cwds/cals/service/FacilityService.java
src/main/java/gov/ca/cwds/cals/service/FacilityTypeService.java
src/main/java/gov/ca/cwds/cals/service/LisFacilityService.java
src/test/java/gov/ca/cwds/cals/web/rest/facility/FacilityResourceTest.java

- https://osi-cwds.atlassian.net/browse/SEAR-85
Additional condition added to not allow to return Facilities not related to child residential in Get Facility by Id API

SEAR-85: not allow to return Facilities not related to child residential in Get Facility by Id API

---

src/main/java/gov/ca/cwds/cals/persistence/model/calsns/dictionaries/FacilityType.java
src/test/resources/fixtures/dictionary/facility-type-response.json

https://osi-cwds.atlassian.net/browse/SEAR-100
Made facility types sort by value(name)
No configuration changes needed
No technical debt introduced

SEAR-100 Sort is not in alphabetical order for 'Facility Type' dropdown

---

build.gradle
src/test/resources/fixtures/dictionary/county-type-response.json

- https://osi-cwds.atlassian.net/browse/AARA-222
County code for State of California changed to be the same as in Perry

AARA-222: County code for State of California changed to be the same as in Perry

---

src/test/java/gov/ca/cwds/cals/web/rest/DictionariesResourceTest.java

https://osi-cwds.atlassian.net/browse/SEAR-100
Fixed path to facility-type-response-pg.json

SEAR-100 added path to facility-type-response-pg.json

---

src/main/java/gov/ca/cwds/cals/service/mapper/AddressMapper.java
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityAddressMapper.java
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityMapper.java
src/test/resources/fixtures/facility/facility-by-id-with-zero-in-county-and-facility-type-response.json

- https://osi-cwds.atlassian.net/browse/SEAR-103
Facility mailing address removed for CWS/CMS facilities

SEAR-103: Facility mailing address removed for CWS/CMS facilities

---

build.gradle

Data model version update

---

src/test/resources/mapping/CountyLicenseCase.sql
src/test/resources/mapping/PlacementHome.sql

- https://osi-cwds.atlassian.net/browse/AARA-225
Mapping for County License Case added for future development. Placement Home mapping expanded information related to License.

AARA-225: mapping for County License Case

---

build.gradle
src/main/java/gov/ca/cwds/cals/persistence/model/fas/Rr809Dn.java

- https://osi-cwds.atlassian.net/browse/SEAR-187
new version of data model and minor changes of an entity to remove deleted columns

SEAR-187: new version of data model and minor changes of entity

---

build.gradle
config/cals-api-lis-connx.yml
config/cals-api.yml
src/test/java/gov/ca/cwds/cals/BaseCalsApiIntegrationTest.java
src/test/java/gov/ca/cwds/cals/persistence/DBUnitSupportBuilder.java
src/test/resources/config/test-cals-api.yml

https://osi-cwds.atlassian.net/browse/SEAR-153
Upgraded core-api version to address "hash code" bottleneck.
Removed excess datasource configuration
Please pay attention that cmsRsDataSourceFactory was removed in all yml files.
N/A

SEAR-153 removed excess dataSourceFactory in configuration, upgraded core-api version

---

build.gradle
src/main/java/gov/ca/cwds/cals/CalsApiApplication.java
src/main/java/gov/ca/cwds/cals/inject/ApplicationModule.java
src/main/java/gov/ca/cwds/cals/inject/DataAccessModule.java
src/main/java/gov/ca/cwds/cals/inject/ServicesModule.java
src/main/java/gov/ca/cwds/cals/persistence/dao/lis/LisTableFileDao.java
src/main/java/gov/ca/cwds/cals/persistence/model/lisfas/LisTableFile.java
src/main/java/gov/ca/cwds/cals/service/LisDictionariesCache.java
src/main/java/gov/ca/cwds/cals/service/LisFacilityService.java

- https://osi-cwds.atlassian.net/browse/SEAR-151
A Cache for LIS dictionaries was created
N/A
N/A

SEAR-151 Slow access to Profile Page when pulling Facility Information

---

build.gradle
src/main/java/gov/ca/cwds/cals/inject/DataAccessModule.java
src/main/java/gov/ca/cwds/cals/service/FacilityChildCollectionService.java
src/main/java/gov/ca/cwds/cals/service/FacilityChildService.java
src/main/java/gov/ca/cwds/cals/service/dao/CustomDao.java
src/main/java/gov/ca/cwds/cals/service/dao/FacilityChildDao.java
src/main/java/gov/ca/cwds/cals/service/dto/ChildPlacementInformation.java
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityChildMapper.java
src/test/java/gov/ca/cwds/cals/web/rest/facility/FacilityChildResourceTest.java
src/test/resources/fixtures/facility/facility-children-response.json

https://osi-cwds.atlassian.net/browse/SEAR-153 
Fix for second out of three bottlenecks - Child Placement Information
N/A

SEAR-153 Slow access to Profile Page when pulling Children Information

---

src/main/java/gov/ca/cwds/cals/service/FacilityChildCollectionService.java

https://osi-cwds.atlassian.net/browse/SEAR-153
Fixed bug preventing facilities without children from showing
N/A
No

SEAR-153 fixed facilities without children

---

mocks/tracking/applicant_documents_template.json
mocks/tracking/family_documents_template.json
mocks/tracking/other_adult_documents_template.json
mocks/tracking/tracking.json

- https://osi-cwds.atlassian.net/browse/AARA-396
Tracking templates update

AARA-396: tracking templates update

---

src/main/java/gov/ca/cwds/cals/inject/ResourcesModule.java
src/main/java/gov/ca/cwds/cals/persistence/dao/calsns/TrackingDao.java
src/main/java/gov/ca/cwds/cals/persistence/model/calsns/tracking/Tracking.java
src/main/java/gov/ca/cwds/cals/service/tracking/RFA1aTrackingService.java
src/main/java/gov/ca/cwds/cals/web/rest/parameter/TrackingParameterObject.java
src/main/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aFormsResource.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/TrackingTest.java

- https://osi-cwds.atlassian.net/browse/AARA-399

AARA-399: Implement RFA Tracking GET API

---

src/main/java/gov/ca/cwds/cals/persistence/model/calsns/tracking/Tracking.java
src/main/java/gov/ca/cwds/cals/service/dto/tracking/TrackingDTO.java
src/main/java/gov/ca/cwds/cals/service/mapper/TrackingMapper.java
src/main/java/gov/ca/cwds/cals/service/tracking/builder/TrackingDocumentsBuilder.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/TrackingTest.java

- https://osi-cwds.atlassian.net/browse/AARA-398
Bugfix
N/A
N/A

AARA-398: RFA Tracking POST API

---

src/main/java/gov/ca/cwds/cals/persistence/model/calsns/rfa/RFA1aForm.java
src/main/java/gov/ca/cwds/cals/service/rfa/RFA1aFormService.java
src/main/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aFormsResource.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/RFA1aFormsResourceTest.java
src/test/java/gov/ca/cwds/cals/web/rest/rfa/helper/FormAHelper.java

Delete RFA1aForm endpoint
Fix Integration test
N/A
N/A

Integration test fix

---

build.gradle
src/test/resources/fixtures/facility/complaints-ffa-response.json

https://osi-cwds.atlassian.net/browse/SEAR-171
Adjusted ffa complaints test to be consistent with test data

SEAR-171 updated test with new fake ffa complaints data

---

src/main/java/gov/ca/cwds/cals/service/dto/AssignedWorkerDto.java
src/main/java/gov/ca/cwds/cals/service/dto/FacilityDTO.java
src/main/java/gov/ca/cwds/cals/service/dto/PersonPhoneDTO.java
src/main/java/gov/ca/cwds/cals/service/mapper/DictionaryMapper.java
src/main/java/gov/ca/cwds/cals/service/mapper/FacilityMapper.java
src/test/java/gov/ca/cwds/cals/service/dto/AssignedWorkerDtoTest.java
src/test/resources/fixtures/dto/assigned-worker.json
src/test/resources/fixtures/facility/facility-by-id-response.json
src/test/resources/fixtures/facility/facility-by-id-with-zero-in-county-and-facility-type-response.json
src/test/resources/fixtures/facility/facility-by-license-number-response.json

- https://osi-cwds.atlassian.net/browse/SEAR-230
- https://osi-cwds.atlassian.net/browse/SEAR-231

SEAR-230: facility assigned worker phone and email
